ci: Fix download failure of non-zip artifacts
release job debug log:

Starting download of artifact to: /home/runner/work/LightZone/LightZone/artifacts
##[debug]Failed to download artifact after 2 retries due to Not a valid zip file. Retrying in 5 seconds...
...
Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.