fix: Add java.naming module that is required by logback
Exception in thread "main" java.lang.NoClassDefFoundError: javax/naming/NamingException
        at ch.qos.logback.classic.joran.ModelClassToModelHandlerLinker.link(ModelClassToModelHandlerLinker.java:57)